import type { HairdresserProfile, Service, Review } from '@/types'

export const MOCK_HAIRDRESSERS: HairdresserProfile[] = [
  {
    id: '1',
    user_id: 'u1',
    user: { id: 'u1', email: 'sofia@example.com', full_name: 'Sofia Martini', avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop', role: 'hairdresser', created_at: '', is_active: true },
    bio: 'Coiffeuse passionnée avec 8 ans d\'expérience. Spécialisée en colorations tendance et coupes modernes. Je me déplace à domicile ou vous reçois dans mon salon cosy.',
    specialties: ['Balayage', 'Coloration', 'Coupe moderne'],
    years_experience: 8,
    portfolio_images: [
      'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&h=300&fit=crop',
    ],
    salon_name: 'Studio Sofia',
    salon_address: '12 rue de la Paix, Paris',
    home_service: true,
    salon_service: true,
    latitude: 48.8698,
    longitude: 2.3322,
    city: 'Paris',
    zip_code: '75001',
    subscription_plan: 'vip',
    rating: 4.9,
    review_count: 142,
    is_verified: true,
    is_featured: true,
    created_at: '2023-01-01',
  },
  {
    id: '2',
    user_id: 'u2',
    user: { id: 'u2', email: 'marcus@example.com', full_name: 'Marcus Dubois', avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop', role: 'hairdresser', created_at: '', is_active: true },
    bio: 'Barber et coiffeur homme expert. Spécialiste des coupes tendance, dégradés et soins barbe. Ambiance détendue garantie.',
    specialties: ['Dégradé', 'Barbe', 'Coupe homme'],
    years_experience: 5,
    portfolio_images: [
      'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=300&fit=crop',
    ],
    salon_name: 'Marcus Barber Shop',
    salon_address: '7 avenue Montaigne, Paris',
    home_service: false,
    salon_service: true,
    latitude: 48.8655,
    longitude: 2.3045,
    city: 'Paris',
    zip_code: '75008',
    subscription_plan: 'pro',
    rating: 4.7,
    review_count: 89,
    is_verified: true,
    is_featured: false,
    created_at: '2023-03-15',
  },
  {
    id: '3',
    user_id: 'u3',
    user: { id: 'u3', email: 'amina@example.com', full_name: 'Amina Benali', avatar_url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&h=150&fit=crop', role: 'hairdresser', created_at: '', is_active: true },
    bio: 'Créatrice de looks uniques et audacieux. Experte en tresses, locks et techniques afro. Je crée votre coiffure signature.',
    specialties: ['Tresses', 'Afro', 'Locks'],
    years_experience: 10,
    portfolio_images: [
      'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=400&h=300&fit=crop',
    ],
    home_service: true,
    salon_service: false,
    latitude: 48.858,
    longitude: 2.3522,
    city: 'Paris',
    zip_code: '75004',
    subscription_plan: 'pro',
    rating: 4.8,
    review_count: 203,
    is_verified: true,
    is_featured: true,
    created_at: '2022-06-01',
  },
  {
    id: '4',
    user_id: 'u4',
    user: { id: 'u4', email: 'claire@example.com', full_name: 'Claire Fontaine', avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop', role: 'hairdresser', created_at: '', is_active: true },
    bio: 'Coiffeuse diplômée passionnée de coiffures de mariage et occasions spéciales. Votre big day mérite le meilleur.',
    specialties: ['Mariée', 'Chignons', 'Coiffure événement'],
    years_experience: 6,
    portfolio_images: [
      'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&h=300&fit=crop',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=300&fit=crop',
    ],
    home_service: true,
    salon_service: true,
    salon_name: 'L\'Atelier Claire',
    salon_address: '5 rue des Fleurs, Lyon',
    latitude: 45.748,
    longitude: 4.8357,
    city: 'Lyon',
    zip_code: '69001',
    subscription_plan: 'vip',
    rating: 5.0,
    review_count: 67,
    is_verified: true,
    is_featured: false,
    created_at: '2023-05-01',
  },
]

export const MOCK_SERVICES: Service[] = [
  { id: 's1', hairdresser_id: '1', name: 'Coupe + Brushing', description: 'Coupe personnalisée et brushing', duration_minutes: 60, price: 65, category: 'coupe_femme', is_available: true },
  { id: 's2', hairdresser_id: '1', name: 'Balayage complet', description: 'Balayage naturel et lumineux', duration_minutes: 150, price: 140, category: 'balayage', is_available: true },
  { id: 's3', hairdresser_id: '1', name: 'Coloration', description: 'Coloration complète avec soin', duration_minutes: 90, price: 95, category: 'coloration', is_available: true },
  { id: 's4', hairdresser_id: '2', name: 'Coupe homme', description: 'Coupe + finitions', duration_minutes: 30, price: 28, category: 'coupe_homme', is_available: true },
  { id: 's5', hairdresser_id: '2', name: 'Dégradé américain', description: 'Dégradé précis avec fondu', duration_minutes: 45, price: 35, category: 'coupe_homme', is_available: true },
  { id: 's6', hairdresser_id: '2', name: 'Barbe + Soin', description: 'Taille et soin de barbe', duration_minutes: 30, price: 25, category: 'soin', is_available: true },
  { id: 's7', hairdresser_id: '3', name: 'Tresses africaines', description: 'Tresses box braids ou cornrows', duration_minutes: 180, price: 120, category: 'coupe_femme', is_available: true },
  { id: 's8', hairdresser_id: '3', name: 'Locks dreadlocks', description: 'Création et entretien de locks', duration_minutes: 240, price: 180, category: 'coupe_femme', is_available: true },
  { id: 's9', hairdresser_id: '4', name: 'Coiffure mariée', description: 'Coiffure de mariage sur mesure', duration_minutes: 120, price: 150, category: 'coiffure_mariee', is_available: true },
  { id: 's10', hairdresser_id: '4', name: 'Chignon élégant', description: 'Chignon pour occasion spéciale', duration_minutes: 60, price: 75, category: 'coiffure_mariee', is_available: true },
]

export const MOCK_REVIEWS: Review[] = [
  { id: 'r1', client_id: 'c1', hairdresser_id: '1', booking_id: 'b1', client: { id: 'c1', email: '', full_name: 'Marie L.', role: 'client', created_at: '', is_active: true }, rating: 5, comment: 'Sofia est incroyable ! Mon balayage est exactement comme je le voulais, naturel et lumineux. Je recommande vivement !', is_visible: true, created_at: '2024-01-15' },
  { id: 'r2', client_id: 'c2', hairdresser_id: '1', booking_id: 'b2', client: { id: 'c2', email: '', full_name: 'Laure M.', role: 'client', created_at: '', is_active: true }, rating: 5, comment: 'Prestation à domicile parfaite. Sofia est ponctuelle, professionnelle et le résultat est magnifique.', is_visible: true, created_at: '2024-01-20' },
  { id: 'r3', client_id: 'c3', hairdresser_id: '2', booking_id: 'b3', client: { id: 'c3', email: '', full_name: 'Thomas R.', role: 'client', created_at: '', is_active: true }, rating: 5, comment: 'Le meilleur barber de Paris ! Marcus sait exactement ce qu\'on veut même sans trop expliquer.', is_visible: true, created_at: '2024-01-18' },
]

export const TIME_SLOTS = [
  '09:00', '09:30', '10:00', '10:30', '11:00', '11:30',
  '12:00', '12:30', '14:00', '14:30', '15:00', '15:30',
  '16:00', '16:30', '17:00', '17:30', '18:00', '18:30',
]
